server:
  port: 1525
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ihis
    username: meenakshi
    password: Meenu@124
    driver-class-name: com.mysql.jdbc.Driver
    

  jpa:
    hibernate:
      ddl-auto: 'update'
    show-sql: true
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: rajshilpa124@gmail.com
    password: Shilparaj@124
    properties:
      mail:
      smtp:
        starttls:
          enable: true
        auth: true
  messages:
    basename: messages     
      
